import { cn } from "@/lib/utils";
import Image from "next/image";
import Section from "../layout/section-box";
import LandingPageContainer from "./LandingPageContainer";
import { Card } from "../ui/card";
import { HeadingPara } from "../layout/heading";
import HeroBubbles from "./hero-bubbles";


export  const earnings = [
    { src: "/assets/landingPage/hero/earning-1.png", alt: "Property 1", amount: "$285.34 ", shares: 69 },
    { src: "/assets/landingPage/hero/earning-5.png", alt: "Property 2", amount: "$271", shares: 57 },
    { src: "/assets/landingPage/hero/earning-3.png", alt: "Property 3", amount: "$334.76", shares: 20 },
    { src: "/assets/landingPage/hero/earning-4.png", alt: "Property 4", amount: "$255.76", shares: 60 },
    { src: "/assets/landingPage/hero/earning-2.png", alt: "Property 5", amount: "$152.64", shares: 34 },
    { src: "/assets/landingPage/hero/earning-1.png", alt: "Property 6", amount: "$319.48", shares: 72 },
    { src: "/assets/landingPage/hero/earning-3.png", alt: "Property 7", amount: "$237.8", shares: 53 },
    { src: "/assets/landingPage/hero/earning-3.png", alt: "Property 7", amount: "$237.8", shares: 53 },
  ];

export default function Partners() {
  // Array of logos
  const logos = [
    {
      src: "/assets/landingPage/hero/1.png",
      alt: "1",
      // style: 'w-28 3xl:w-28'
    },
    {
      src: "/assets/landingPage/hero/2.png",
      alt: "2",
      // style: 'w-20 3xl:w-24'
    },
    {
      src: "/assets/landingPage/hero/3.png",
      alt: "3",
      // style: 'w-16 3xl:w-20'
    },
    {
      src: "/assets/landingPage/hero/4.png",
      alt: "4",
      // style: 'w-20 3xl:w-28'
    },
    {
      src: "/assets/landingPage/hero/5.png",
      alt: "5",
      // style: 'p-1 w-20 3xl:w-24'
    },
    {
      src: "/assets/landingPage/hero/6.png",
      alt: "6",
      // style: 'w-32 3xl:w-36'
    },
    {
      src: "/assets/landingPage/hero/7.png",
      alt: "7",
      // style: 'w-32 3xl:w-36'
    }
  ];



  // const isSmallScreen = useMediaQuery('max-width: ')

  return (
    <Section className="bg-cream">
      <LandingPageContainer className="py-12 3xl:py-16 !pt-0 space-y-12 3xl:space-y-20">

        <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-7 xl:gap-6 3xl:gap-0 items-center justify-center md:justify-between container mx-auto px-4 max-w-6xl w-full pt-6 sm:pt-2">
          {logos.map((logo, index) => (
            <div
              key={index}
              className={`flex justify-center items-center p-2 w-full ${index === 6 ? 'col-span-full xl:col-span-1' : ''}`}
            >
              <Image
                src={logo.src}
                alt={logo.alt}
                width={100}
                height={100}
                quality={100}
                className={cn(`hover:opacity-80 transition-opacity duration-300 max-w-full h-full object-contain w-2/4 sm:w-2/5 md:2/5 lg:w-1/4 xl:w-3/4`,
                  // logo.style
                  index === 6 && 'w-1/3 sm:w-1/6 md:w-[12%] lg:w-[10%] xl:w-2/3'
                )}
              />
            </div>
          ))}
        </div>

        <Card className="bg-center bg-cover bg-no-repeat w-full text-center flex items-center justify-center shadow-none overflow-hidden"
          style={{ backgroundImage: 'url(/assets/landingPage/hero/partner-card-bg.png)' }}>
          <div className="container mx-auto px-2 xs:px-4 py-6 xs:py-8 lg:py-16 grid grid-cols-1 lg:grid-cols-2 lg:gap-16 items-center">
            {/* left: bubbles */}
            <HeroBubbles earnings={earnings} />

            {/* right: headline + subcopy */}
            <div className="space-y-6 text-white text-center lg:text-right xl:pr-10 3xl:pr-16">
              <HeadingPara title="Where Digital Ownership Meets Real‑World Opportunity" classNameTitle="text-2xl xl:text-3xl 3xl:text-4xl font-heading" />
              <p className="text-lg lg:text-xl ">
                Earn passive income from the rent collected on properties or the profits
                generated by tokenized businesses. It’s real yield, not speculative hype.
              </p>
            </div>
          </div>
        </Card>

      </LandingPageContainer>
    </Section >
  );
}
